"""add clinic memberships

Revision ID: 055a1969e747
Revises: 1f8a209c2b67
Create Date: 2026-08-03 18:51:10.700105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055a1969e747'
down_revision: Union[str, Sequence[str], None] = '1f8a209c2b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), server_default='staff', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_memberships_id'), 'clinic_memberships', ['id'], unique=False)
    op.execute("""
        INSERT INTO clinic_memberships (user_id, clinic_id, role)
        SELECT id, clinic_id, role FROM users
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinic_memberships_id'), table_name='clinic_memberships')
    op.drop_table('clinic_memberships')
    # ### end Alembic commands ###
