"""add expected_qty to stock movements

Revision ID: 6b7d92980c9b
Revises: 7bf811587ee3
Create Date: 2026-07-30 23:48:13.672358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7d92980c9b'
down_revision: Union[str, Sequence[str], None] = '7bf811587ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('expected_qty', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'expected_qty')
    # ### end Alembic commands ###
