"""add roles, password resets, supplier fields, movement user

Revision ID: 7bf811587ee3
Revises: c092a649f7ac
Create Date: 2026-07-30 23:02:20.967054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf811587ee3'
down_revision: Union[str, Sequence[str], None] = 'c092a649f7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.add_column('items', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('supplier_sku', sa.String(), nullable=True))
    op.add_column('items', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('stock_movements', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), server_default='staff', nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'active')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'user_id')
    op.drop_column('items', 'unit_cost')
    op.drop_column('items', 'supplier_sku')
    op.drop_column('items', 'supplier_name')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
