"""add supplier_email and auto_reorder to items

Revision ID: b8f5feb9a0bf
Revises: eda4eaea574b
Create Date: 2026-08-10 21:46:16.761300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f5feb9a0bf'
down_revision: Union[str, Sequence[str], None] = 'eda4eaea574b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('supplier_email', sa.String(), nullable=True))
    op.add_column('items', sa.Column('auto_reorder', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'auto_reorder')
    op.drop_column('items', 'supplier_email')
    # ### end Alembic commands ###
