"""add pack unit and pack size to items

Revision ID: c092a649f7ac
Revises: ed3052a691c1
Create Date: 2026-07-29 23:15:55.632219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c092a649f7ac'
down_revision: Union[str, Sequence[str], None] = 'ed3052a691c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('pack_unit', sa.String(), nullable=True))
    op.add_column('items', sa.Column('pack_size', sa.Numeric(precision=12, scale=2), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'pack_size')
    op.drop_column('items', 'pack_unit')
    # ### end Alembic commands ###
