"""add lot tracking model

Revision ID: c2997186b93e
Revises: e2de52269c08
Create Date: 2026-08-03 18:40:28.270223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2997186b93e'
down_revision: Union[str, Sequence[str], None] = 'e2de52269c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_lots_id'), 'item_lots', ['id'], unique=False)
    op.add_column('items', sa.Column('tracking_mode', sa.String(), server_default='quantity', nullable=False))
    op.add_column('stock_movements', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'item_lots', ['lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'lot_id')
    op.drop_column('items', 'tracking_mode')
    op.drop_index(op.f('ix_item_lots_id'), table_name='item_lots')
    op.drop_table('item_lots')
    # ### end Alembic commands ###
