"""add supplier_email and auto_reorder to items

Revision ID: eda4eaea574b
Revises: 5b0f7879d24f
Create Date: 2026-08-10 21:30:34.172078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda4eaea574b'
down_revision: Union[str, Sequence[str], None] = '5b0f7879d24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
